### PR TITLE
Bundle the `xsel` binary

### LINKED ISSUE #3: Fallback to xclip
On GNU+Linux, there are two common programs for clipboard access. `xsel` is already implemented, but `xclip` could be as well. If ran without any flags, it accepts stdin and writes it to the clipboard buffer. If passed in `-o`, it outputs the clipboard buffer to stdout.

https://qa.debian.org/popcon.php?package=xclip
https://qa.debian.org/popcon.php?package=xsel

They have almost the same amount of installs on popcon!

### PR DESCRIPTION
**Pull request by floatdrop**
This should fix #3 and allow to export platform specific API in future.

### CODE REVIEW

**Comment by floatdrop** [comment]
Not sure why `xclip` hangs – is it waiting for input? @misterhat @sindresorhus

**Comment by sindresorhus** [comment]
> Not sure why xclip hangs – is it waiting for input?

I don't know either. See my comment in the issue:

> I had problems getting xclip to work when spawned. It stalled forever until I copied something while it was running.

**Comment by sindresorhus** [comment]
> About the "just working", xclip is an incredibly tiny program and we could make an optional pre-built dependency for it if you wanted.

Could we do this too?

**Comment by floatdrop** [comment]
@sindresorhus I think we can bundle [xsel](https://github.com/kfish/xsel) – just because it is working.

**Comment by floatdrop** [comment]
> Could we do this too?

@sindresorhus done.

**Comment by Qix-** [comment]
Maybe I'm missing something, but this PR doesn't actually fall back to xclip at all... I don't see `xclip` being invoked anywhere.

**Comment by floatdrop** [comment]
@Qix- yeah, I decided to drop it. There is no need to fallback on `xclip`, because `xsel` is bundled, so it will be always available (and `xclip` is working very strangely).

**Comment by Qix-** [comment]
Oh okay haha, I was incredibly confused. Perhaps update the title? 💃

**Comment by sindresorhus** [comment]
It should fall back to the system `xsel` if for some reason the bundled one doesn't work. It's almost impossible to create a binary that works everywhere on Linux.

**Comment by floatdrop** [comment]
@sindresorhus sure thing. Done.

**Comment by sindresorhus** [comment]
Looks good. Thank you @floatdrop :)

**Pull request merged**
