### PR TITLE
Fix unicode support on Windows

### LINKED ISSUE #2: Probably doesn't work as expected on some Windows machines
node-copy-paste uses the same method of execing `clip` on Windows but I had some trouble with Unicode characters on systems running ASCII-only code pages (for instance, those configured with en-US locales).

I've addressed this in my [fork of node-copy-paste](https://github.com/notatestuser/node-copy-paste/tree/master/platform/fallbacks) by setting the code page to `65001` before running `clip.exe`.

`execa` might already be handling this but I'm not sure.

### LINKED ISSUE #11: UTF-8 issues on Windows 10
This is related to #2, I think his fix will most likely work, I also followed this issue on the other popular copy paste library.

Run the following test:

test.only('works with unicode', async t => {
	const f = '你好';
	t.is(await writeRead(f), f);
});

Now open any other program, notepad etc, and do Edit-Copy or Ctrl+V and you will get Σ╜áσÑ╜.

This is going to be difficult to write a test for since from the libraries standpoint, everything is good. Outside of the library however, it is not actually working with the correct clipboard contents due to encoding.

### PR DESCRIPTION
**Pull request by sindresorhus**
I decided to code my own binaries as existing hacks were just too slow and fragile.

https://github.com/sindresorhus/win-clipboard

Fixes #11 
Fixes #2

### CODE REVIEW

**Comment by sindresorhus** [comment]
@notatestuser @xconverge Can you test and confirm it's working?

**Comment by xconverge** [comment]
is there code for the binary here somewhere?

**Comment by sindresorhus** [comment]
@xconverge Yes, see the above link.

**Comment by xconverge** [comment]
Woops sorry didn't see it! I'll test it on Windows tomorrow!

**Comment by xconverge** [comment]
This looks good on my machine! Thanks a lot for the quick turnaround, this is going to be help out a lot

**Comment by notatestuser** [comment]
Hooray - great to see you've finally acknowledged this as an issue after my ticket got ninja-closed 5 months ago. This works for me.

**Comment by sindresorhus** [comment]
@notatestuser Sorry about that. I get 100+ issues a week, of which 95% are invalid. I took a closer look this time as two people encountering something is a sign that it actually *is* an issue, and @xconverge provided manual steps to reproduce, which made it easy for me to confirm.

**Pull request merged**
