### PR TITLE
Set LC_CTYPE to UTF-8 on macOS

### LINKED ISSUE #15: Default LC_TYPE
> pbcopy and pbpaste use locale environment variables to determine the encoding to be used for input and output. For example, absent other locale settings, setting the environment variable LANG=en_US.UTF-8 will cause pbcopy and pbpaste to use UTF-8 for input and output. If an encoding cannot be determined from the locale, the standard C encoding will be used. Use of UTF-8 is recommended. Note that by default the Terminal application uses the UTF-8 encoding and automatically sets the appropriate locale environment variable.

https://github.com/Microsoft/vscode/issues/26502#issuecomment-301043547

Should we set `UTF-8` as default encoding, if no specified?

### PR DESCRIPTION
**Pull request by floatdrop**
Closes #15

### CODE REVIEW

**Comment by sindresorhus** [comment]
No, I meant we should override whatever the user have. It should always be UTF8. Both for consistency and to prevent user mistakes.

**Comment by sindresorhus** [comment]
Instead pass it as the `env` option to `execa`: https://github.com/sindresorhus/clipboardy/blob/5c610c36d270009d1580f4cc6263a8f13c69d19c/lib/macos.js#L5

**Comment by sindresorhus** [comment]
Tests are failing since you're overriding `env` which contains the `PATH`, so it can no longer find the binaries. You also need to `Object.assign()` the `env` option. I guess it would be useful if `execa` had an `extendEnv` option, as I've fallen for this before too.

**Comment by floatdrop** [comment]
@sindresorhus thanks for tips! `extendEnv` is good idea.

screen shot 2017-05-13 at 14 38 20

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/execa/issues/87

**Comment by sindresorhus** [comment]
Great! Thanks for fixing this :)

**Pull request merged**
